apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo
  namespace: todo
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-todo
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
      - "namespaces"
      - "endpoints"
    verbs:
      - "get"
      - "post"
      - "put"
      - "delete"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: todo
  name: service-todo
subjects:
  - kind: ServiceAccount
    name: todo
    namespace: todo
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: service-todo
  apiGroup: ""