name: sample/sampleapp Build and Push
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "backend/sample/sampleapp/**/*.go"
      - "backend/kit/**/*.go"
jobs:
  # Build the image of the service and push it
  build-and-push:
    uses: mukhtarkv/workspace/.github/workflows/ko-builder.yaml@main
    with:
      service: sampleapp
      namespace: sample
